### PR TITLE
Fix security vulnerability

### PR DESCRIPTION
**Pull request by bblaisATcoveo**
Fix XSS security vulnerability found on Sunday July 7th 2024

### CODE REVIEW

**Comment by bblaisATcoveo** [comment]
@duboisp Here's the PR for the security vulnerability found this weekend

**Review by duboisp — CHANGES_REQUESTED** [review]
Can you scan the whole file and ensure that all the user entries point are sanitized? 

For example, I don't see any sanitization here when the data is taken from the URL: https://github.com/ServiceCanada/search-ui/blob/main/src/connector.js#L621 
and I don't see any change related to sanitize the value of the text input.

**Comment by duboisp** [comment]
@bblaisATcoveo not mandatory but I would appreciate if you can remove the "merge commit" from your PR because it does introduce useless new commit and it could include regression error. Also, it will be cleaner and easier to see the change you did. Thanks

**Comment by bblaisATcoveo** [comment]
> @bblaisATcoveo not mandatory but I would appreciate if you can remove the "merge commit" from your PR because it does introduce useless new commit and it could include regression error. Also, it will be cleaner and easier to see the change you did. Thanks

Just not sure what's the best way to do this , simply delete/recreate  my fork then recreate the PR?

**Comment by bblaisATcoveo** [comment]
> Can you scan the whole file and ensure that all the user entries point are sanitized?
> 
> For example, I don't see any sanitization here when the data is taken from the URL: https://github.com/ServiceCanada/search-ui/blob/main/src/connector.js#L621 and I don't see any change related to sanitize the value of the text input.

Yes i did scan the entire file, i didn't find another issue, the fragment method looks good to me, we will reparse/sanitize the parameters after
just pushed a change to double-sanitize whatever we put in the search box, just to stay on the safe side.

**Comment by duboisp** [comment]
@bblaisATcoveo 

> Yes i did scan the entire file, i didn't find another issue, 

What about the search input `id=sch-inp-ac`? Is that value are sanitized prior to process? I think the value is captured in all those place here : 
* https://github.com/ServiceCanada/search-ui/blob/main/src/connector.js#L692
* https://github.com/ServiceCanada/search-ui/blob/main/src/connector.js#L713

---

> Just not sure what's the best way to do this 

You can reset hard to the upstream/main, then you git cherry-pick the commit that are applying changes related to this pr

```
git reset --hard upstream/main
git cherry-pick 83bc01825ee334ae0c485e854d3d2c720ec13b64
git cherry-pick 149dafa2f44c6f1c7baa14e6022f5fcef07f177e
...
Until the last commit you did
```

You can use the commit list in this PR to know what is the commit sha

**Comment by bblaisATcoveo** [comment]
> @bblaisATcoveo
> 
> > Yes i did scan the entire file, i didn't find another issue,
> 
> What about the search input `id=sch-inp-ac`? Is that value are sanitized prior to process? I think the value is captured in all those place here :
> 
> * https://github.com/ServiceCanada/search-ui/blob/main/src/connector.js#L692
> * https://github.com/ServiceCanada/search-ui/blob/main/src/connector.js#L713
> 
> > Just not sure what's the best way to do this
> 
> You can reset hard to the upstream/main, then you git cherry-pick the commit that are applying changes related to this pr
> 
> ```
> git reset --hard upstream/main
> git cherry-pick 83bc01825ee334ae0c485e854d3d2c720ec13b64
> git cherry-pick 149dafa2f44c6f1c7baa14e6022f5fcef07f177e
> ...
> Until the last commit you did
> ```
> 
> You can use the commit list in this PR to know what is the commit sha

@duboisp the Coveo headless framework offers built-in protection so i'm not worried about the content we send to those calls
i'll take a look at the proposed solution to reduce the commits

**Comment by bblaisATcoveo** [comment]
> > @bblaisATcoveo
> > > Yes i did scan the entire file, i didn't find another issue,
> > 
> > 
> > What about the search input `id=sch-inp-ac`? Is that value are sanitized prior to process? I think the value is captured in all those place here :
> > 
> > * https://github.com/ServiceCanada/search-ui/blob/main/src/connector.js#L692
> > * https://github.com/ServiceCanada/search-ui/blob/main/src/connector.js#L713
> > 
> > > Just not sure what's the best way to do this
> > 
> > 
> > You can reset hard to the upstream/main, then you git cherry-pick the commit that are applying changes related to this pr
> > ```
> > git reset --hard upstream/main
> > git cherry-pick 83bc01825ee334ae0c485e854d3d2c720ec13b64
> > git cherry-pick 149dafa2f44c6f1c7baa14e6022f5fcef07f177e
> > ...
> > Until the last commit you did
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can use the commit list in this PR to know what is the commit sha
> 
> @duboisp the Coveo headless framework offers built-in protection so i'm not worried about the content we send to those calls i'll take a look at the proposed solution to reduce the commits

I performed the hard reset and cherry picking, it didn't remove the old commits so not sure if it really worked...

**Comment by duboisp** [comment]
@bblaisATcoveo  Did you get an error when resetting hard? is the uptream remote are defined in your local git? "git remote -v" did you fetch it all before. "git fetch --all"

**Comment by bblaisATcoveo** [comment]
i'll try again with a git fetch --all first

**Comment by duboisp** [comment]
@bblaisATcoveo I don't see the change to sanitize the content coming from the input field (at L692 and L713). Or is it sanitized somewhere else before any processing?

**Review by duboisp — COMMENTED** [review]
It looks good.

I am going to do a small local test prior to merge this.

**Review by duboisp — CHANGES_REQUESTED** [review]
J'ai testé avec quelque requête et j'ai remarqué un comportement qui n'est pas attendu. Je t'envoie les details via le chat.

**Review by duboisp — CHANGES_REQUESTED** [review]
2 of my test are still failing. I sent you the details in the chat.

**Review by duboisp — CHANGES_REQUESTED** [review]
I found there was a conflict with the data-fusion plugin which was used by our old search interface. The PR #11 are resolving that issue.

I tested the solution and it is working as expected after the change to the search ui is applied.

Once all the console logs and the test token is removed, we will be able to merge this PR. 

Thank you

**Review by duboisp — APPROVED** [review]
Reviewed and tested locally

It does work as expected.

**Pull request merged**
