### PR TITLE
Release v1.4.0

### PR DESCRIPTION
**Pull request by GormFrank**

### CODE REVIEW

**Review by duboisp — CHANGES_REQUESTED** [review]
I reviewed the diff between commit 9fa2388f03f97df857ab10f6a56798684d38f326 and v1.3.0 (which is a total of 2 commits) and I did checked the release note.

So far so good. Note that I remark that its no demo/test that are illustrating all functionality. For example, there is additional feature available by providing custom HTML template that are not demoed. Not a blocker, but the working example should be improved (Enlarge its code coverage) or add unit testing for the next release of the search ui.

Request change is about the item "Patch: API - This is to fix API calls for Analytics, which would fail when cookies are turned off". I am unable to link that change with any of the code change. How can I validate that item by looking at the search-ui source code? Thanks for providing me the line of code illustrating that change.

**Comment by GormFrank** [comment]
@duboisp It is this line, illustrated in the recently merged PR: https://github.com/ServiceCanada/search-ui/pull/24/files#diff-5bf845b8b5d0fb5fc819cfcd30b5d4fc1701eb6726a6323e250ebdd9379c7a2fR435

It was observed that an error would be thrown when cookies are disable and that the code was trying to run `requestContent.analytics.originLevel3` since in that case the `.analytics` is undefined. Adding the `if` statement prevents from having this error, and will not log analytics in the case of disabled cookies, with respect to the user's privacy settings.

Therefore, maybe the wording isn't quite optimal in the release notes: "This is to fix API calls for Analytics, which would fail when cookies are turned off", it could be instead "This is to fix search functionalities when cookies are turned off"

**Comment by duboisp** [comment]
Thanks for the explanation. I am going to do a quick functional test now

**Review by duboisp — CHANGES_REQUESTED** [review]
Please rebase your PR, the commit 9fa2388f03f97df857ab10f6a56798684d38f326 is not there

**Comment by GormFrank** [comment]
> Please rebase your PR, the commit [9fa2388](https://github.com/ServiceCanada/search-ui/commit/9fa2388f03f97df857ab10f6a56798684d38f326) is not there

Done!

**Review by duboisp — APPROVED** [review]

**Pull request merged**
